on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: rlucas7/hw-js-action@5c814e21532f9643027b94a5d3c7ab13377f8ca0
        with:
          who-to-greet: Meow cat

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

